### ISSUE TITLE
Error with files starting from .

### ISSUE THREAD

**Issue by dimmduh** [3pjgames/unity-git-hooks#7]
![image](https://user-images.githubusercontent.com/446814/87121163-bf715980-c2b4-11ea-8861-19c61bf2e250.png)

It seems unity ignore these files, but it's in repository
I use nuget client for unity

![image](https://user-images.githubusercontent.com/446814/87121248-f182bb80-c2b4-11ea-8936-7d21fc38309e.png)
![image](https://user-images.githubusercontent.com/446814/87121266-fcd5e700-c2b4-11ea-8362-a4c908edd991.png)

**Comment by doitian** [comment]
Can you confirm whether this version fixes the issue?
https://github.com/doitian/unity-git-hooks/blob/bbd72b4c710ac28e0501015f85bd48ac06a75d44/scripts/pre-commit

**Comment by dimmduh** [comment]
sorry, 8 gb project, I renamed folder from !Project to 1Project
can not easy revert and check(
thx for fix
