### ISSUE TITLE
pre-commit can not deal with rename directory

### ISSUE THREAD

**Issue by xtutu** [3pjgames/unity-git-hooks#9]
when rename a directory, and without create a meta file.
pre-commit can not prevent this case.

**Comment by doitian** [comment]
Test case to reproduce:

1. Add a directory and its meta file to git. Git does not allow adding a directory, so add a `.gitkeep` file in the directory.
2. Rename the directory without renaming the meta file.

- Expected result: pre-commit should report the error
- Real result: pre-commit passed
- Cause: `git diff` will exclude detected renames from adds and deletes, so the script does not check all renames.

```bash
@test "renaming directory" {
  mkdir Assets/dir
  touch Assets/dir/.gitkeep
  touch Assets/dir.meta
  git add --force --all
  git commit -n -m 'add Assets/dir'
  mv Assets/dir Assets/dir-new
  git add --force --all
  run "$PRE_COMMIT"
  [ "$status" -eq 0 ]
}
```
